server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-threads: 400
    max-connections: 10000
spring:
  application:
    name: cassandra-example
  data:
    cassandra:
      keyspaceName: pl
      contactPoints: 10.6.xxx
      port: 9042
      entityBasePackages: com.example.cassandra.entity
      localDataCenter: datacenter1

  redis:
    redisson:
      config: classpath:redisson-single-dev.yaml


knife4j:
  basic:
    ## 开启Swagger的Basic认证功能,默认是false
    enable: true
    ### Basic认证用户名
    username: sinodata
    ### Basic认证密码
    password: 123