server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    max-threads: 400
    max-connections: 10000
spring:
  application:
    name: cassandra-example
  data:
    cassandra:
      keyspaceName: pa
      contactPoints: 10.6.136.111
      port: 9042
      entityBasePackages: com.sinodata.example.cassandra.entity
      localDataCenter: datacenter1

  redis:
    host: 10.6.136.80   # Redis服务器地址
    database: 0         # Redis数据库索引（默认为0）
    port: 6379          # Redis服务器连接端口
    password:           # Redis服务器连接密码（默认为空）
    timeout: 3000       # 连接超时时间（毫秒）
    pool:
      max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 100   # 连接池中的最大空闲连接
      min-idle: 0     # 连接池中的最小空闲连接
      timeout: 3000   # 连接超时时间（毫秒）


knife4j:
  basic:
    ## 开启Swagger的Basic认证功能,默认是false
    enable: true
    ### Basic认证用户名
    username: sinodata
    ### Basic认证密码
    password: 123